version: "3.8"

services:
  app:
    build: .
    ports:
      - "3030:3030"
    depends_on:
      - db
    networks:
      - app-network
    env_file:
      - .env

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    networks:
      - app-network
    env_file:
      - .env

networks:
  app-network:
